
CREATE TABLE users (
                       id INT AUTO_INCREMENT PRIMARY KEY,
                       email VARCHAR(255) UNIQUE NOT NULL,
                       password VARCHAR(500) NOT NULL,
                       fullname VARCHAR(500) NOT NULL,
                       status VARCHAR(500) NOT NULL, -- Các giá trị: 'ACTIVE', 'BLOCK'
                       role VARCHAR(50) NOT NULL     -- Các giá trị: 'ADMIN', 'USER'
);
INSERT INTO users (email, password, fullname, status, role) VALUES
                                                                ('messi10@example.com', 'passmessi', 'Lionel Messi', 'ACTIVE', 'USER'),
                                                                ('cristiano7@example.com', 'passronaldo', 'Cristiano Ronaldo', 'ACTIVE', 'ADMIN'),
                                                                ('neymar11@example.com', 'passneymar', 'Neymar Jr', 'BLOCK', 'USER'),
                                                                ('mbappe7@example.com', 'passmbappe', 'Kylian Mbappé', 'ACTIVE', 'USER'),
                                                                ('haaland9@example.com', 'passhaaland', 'Erling Haaland', 'ACTIVE', 'USER'),
                                                                ('lewandowski9@example.com', 'passlewa', 'Robert Lewandowski', 'BLOCK', 'USER'),
                                                                ('modric10@example.com', 'passmodric', 'Luka Modrić', 'ACTIVE', 'USER'),
                                                                ('benzema9@example.com', 'passbenz', 'Karim Benzema', 'ACTIVE', 'USER'),
                                                                ('kroos8@example.com', 'passkroos', 'Toni Kroos', 'BLOCK', 'USER'),
                                                                ('vinijr20@example.com', 'passvini', 'Vinícius Júnior', 'ACTIVE', 'USER'),
                                                                ('kante7@example.com', 'passkante', 'N\'Golo Kanté', 'ACTIVE', 'ADMIN'),
                                                                ('rashford10@example.com', 'passrash', 'Marcus Rashford', 'BLOCK', 'USER'),
                                                                ('son7@example.com', 'passson', 'Heung-Min Son', 'ACTIVE', 'USER'),
                                                                ('griezmann7@example.com', 'passgriez', 'Antoine Griezmann', 'ACTIVE', 'USER'),
                                                                ('salah11@example.com', 'passsalah', 'Mohamed Salah', 'ACTIVE', 'USER'),
                                                                ('mane10@example.com', 'passmane', 'Sadio Mané', 'BLOCK', 'USER'),
                                                                ('firmino9@example.com', 'passfirmino', 'Roberto Firmino', 'ACTIVE', 'USER'),
                                                                ('foden47@example.com', 'passfoden', 'Phil Foden', 'ACTIVE', 'USER'),
                                                                ('debruyne17@example.com', 'passkdb', 'Kevin De Bruyne', 'ACTIVE', 'ADMIN'),
                                                                ('courtois1@example.com', 'passcourtois', 'Thibaut Courtois', 'BLOCK', 'USER'),
                                                                ('alisson1@example.com', 'passalisson', 'Alisson Becker', 'ACTIVE', 'USER'),
                                                                ('terstegen1@example.com', 'passtegen', 'Marc-André ter Stegen', 'ACTIVE', 'USER'),
                                                                ('oblak13@example.com', 'passoblak', 'Jan Oblak', 'BLOCK', 'USER'),
                                                                ('donnarumma99@example.com', 'passdonna', 'Gianluigi Donnarumma', 'ACTIVE', 'USER'),
                                                                ('ramos4@example.com', 'passramos', 'Sergio Ramos', 'ACTIVE', 'ADMIN'),
                                                                ('vanDijk4@example.com', 'passvandijk', 'Virgil van Dijk', 'BLOCK', 'USER'),
                                                                ('thiagosilva6@example.com', 'passts', 'Thiago Silva', 'ACTIVE', 'USER'),
                                                                ('alaba4@example.com', 'passalaba', 'David Alaba', 'ACTIVE', 'USER'),
                                                                ('kante13@example.com', 'passngolo', 'N\'Golo Kanté', 'BLOCK', 'USER'),
                                                                ('casemiro14@example.com', 'passcase', 'Casemiro', 'ACTIVE', 'USER'),
                                                                ('bruno8@example.com', 'passbruno', 'Bruno Fernandes', 'ACTIVE', 'USER'),
                                                                ('pedri8@example.com', 'passpedri', 'Pedri González', 'BLOCK', 'USER'),
                                                                ('gavi6@example.com', 'passgavi', 'Gavi', 'ACTIVE', 'USER'),
                                                                ('bellingham5@example.com', 'passbelli', 'Jude Bellingham', 'ACTIVE', 'USER'),
                                                                ('reus11@example.com', 'passreus', 'Marco Reus', 'BLOCK', 'USER'),
                                                                ('sancho25@example.com', 'passsancho', 'Jadon Sancho', 'ACTIVE', 'USER'),
                                                                ('zlatan11@example.com', 'passzlatan', 'Zlatan Ibrahimović', 'ACTIVE', 'ADMIN'),
                                                                ('leao17@example.com', 'passleao', 'Rafael Leão', 'BLOCK', 'USER'),
                                                                ('osimhen9@example.com', 'passosimhen', 'Victor Osimhen', 'ACTIVE', 'USER'),
                                                                ('barella23@example.com', 'passbarella', 'Nicolò Barella', 'ACTIVE', 'USER'),
                                                                ('locatelli5@example.com', 'passloca', 'Manuel Locatelli', 'BLOCK', 'USER'),
                                                                ('pogba6@example.com', 'passpogba', 'Paul Pogba', 'ACTIVE', 'USER'),
                                                                ('camavinga25@example.com', 'passcama', 'Eduardo Camavinga', 'ACTIVE', 'USER'),
                                                                ('valverde15@example.com', 'passvalverde', 'Federico Valverde', 'BLOCK', 'USER'),
                                                                ('musiala42@example.com', 'passmusiala', 'Jamal Musiala', 'ACTIVE', 'USER'),
                                                                ('gnabry7@example.com', 'passgnabry', 'Serge Gnabry', 'ACTIVE', 'USER'),
                                                                ('gundogan8@example.com', 'passgundo', 'İlkay Gündoğan', 'BLOCK', 'USER'),
                                                                ('raphinha11@example.com', 'passraphinha', 'Raphinha', 'ACTIVE', 'USER'),
                                                                ('martinez22@example.com', 'passlautaro', 'Lautaro Martínez', 'ACTIVE', 'USER'),
                                                                ('beck@examle.com','passbeck','Beckham','ACTIVE','USER');

CREATE TABLE product (
                         id INT AUTO_INCREMENT PRIMARY KEY,
                         name VARCHAR(500) NOT NULL,
                         description TEXT,
                         price NUMERIC(10,3) NOT NULL,
                         stock int,
                         original_price NUMERIC(10,3) NOT NULL ,
                         category varchar(255)
);

INSERT INTO product (name, description, price, stock, original_price, category) VALUES
                                                                                    ('iPhone 14 Pro Max', 'Điện thoại cao cấp của Apple với chip A16 Bionic', 29990.000, 15, 26990.000, 'ELECTRONICS'),
                                                                                    ('Sách Atomic Habits', 'Cuốn sách phát triển bản thân bán chạy toàn cầu', 190.000, 50, 160.000, 'BOOKS'),
                                                                                    ('Bàn phím cơ Akko 3068', 'Bàn phím cơ không dây switch Brown', 1590.000, 20, 1390.000, 'ELECTRONICS'),
                                                                                    ('Áo thun Uniqlo nam', 'Chất liệu cotton co giãn, nhiều màu sắc', 299.000, 60, 199.000, 'FASHION'),
                                                                                    ('Máy ép chậm Elmich', 'Máy ép trái cây giữ nguyên dưỡng chất', 2590.000, 10, 2290.000, 'HOME'),
                                                                                    ('Tai nghe Sony WH-1000XM5', 'Tai nghe chống ồn chủ động, pin 30h', 7990.000, 25, 7490.000, 'ELECTRONICS'),
                                                                                    ('Giày Nike Air Force 1', 'Giày sneaker da trắng cổ điển', 2490.000, 18, 2290.000, 'FASHION'),
                                                                                    ('Laptop Dell XPS 13', 'Laptop cao cấp, mỏng nhẹ, pin lâu', 42990.000, 5, 39990.000, 'ELECTRONICS'),
                                                                                    ('Sách Đắc nhân tâm', 'Cuốn sách kinh điển về giao tiếp và thành công', 120.000, 100, 100.000, 'BOOKS'),
                                                                                    ('Loa JBL Flip 6', 'Loa bluetooth chống nước, âm thanh mạnh mẽ', 2490.000, 20, 2190.000, 'ELECTRONICS'),
                                                                                    ('Bàn học gấp gọn', 'Bàn học đa năng cho học sinh sinh viên', 790.000, 40, 690.000, 'HOME'),
                                                                                    ('Tai nghe AirPods Pro 2', 'Tai nghe không dây Apple chống ồn chủ động', 6490.000, 30, 5890.000, 'ELECTRONICS'),
                                                                                    ('Sách Lược sử loài người', 'Khám phá hành trình tiến hóa của nhân loại', 250.000, 45, 220.000, 'BOOKS'),
                                                                                    ('Đồng hồ Casio MTP-VT01L', 'Đồng hồ dây da nam, thiết kế tối giản', 1090.000, 25, 990.000, 'FASHION'),
                                                                                    ('Smartwatch Xiaomi Watch 2', 'Đồng hồ thông minh hỗ trợ đo nhịp tim, GPS', 1990.000, 15, 1790.000, 'ELECTRONICS'),
                                                                                    ('Cặp học sinh chống gù', 'Thiết kế thông minh, siêu nhẹ', 590.000, 40, 520.000, 'STATIONERY'),
                                                                                    ('Nồi chiên không dầu Lock&Lock', 'Dung tích 5L, tiết kiệm dầu mỡ', 1790.000, 12, 1590.000, 'HOME'),
                                                                                    ('Bút máy Thiên Long FT-01', 'Bút viết êm, mực trơn, phù hợp học sinh', 35.000, 100, 29.000, 'STATIONERY'),
                                                                                    ('Google Pixel 8', 'Điện thoại Android tinh gọn, camera AI ấn tượng', 21990.000, 8, 19990.000, 'ELECTRONICS'),
                                                                                    ('Sách Nhà giả kim', 'Tác phẩm nổi tiếng của Paulo Coelho', 150.000, 80, 120.000, 'BOOKS'),
                                                                                    ('Túi đeo chéo thời trang nam', 'Chất vải bố chống nước, nhiều ngăn tiện lợi', 390.000, 60, 320.000, 'FASHION'),
                                                                                    ('Bình giữ nhiệt Lock&Lock', 'Dung tích 500ml, giữ nhiệt 6–12 giờ', 290.000, 50, 249.000, 'HOME'),
                                                                                    ('Ổ cứng SSD Samsung 1TB', 'Tốc độ đọc ghi cực nhanh cho máy tính', 2990.000, 30, 2790.000, 'ELECTRONICS'),
                                                                                    ('Bút bi mực gel Pentel', 'Bút viết trơn, không lem mực', 12.000, 200, 9.000, 'STATIONERY'),
                                                                                    ('Laptop MacBook Air M2', 'Siêu nhẹ, hiệu năng mạnh mẽ với chip M2', 31990.000, 7, 28990.000, 'ELECTRONICS'),
                                                                                    ('Giày Adidas Ultraboost 22', 'Giày chạy bộ thoải mái, đàn hồi tốt', 2990.000, 20, 2590.000, 'FASHION'),
                                                                                    ('Sách Tư duy nhanh và chậm', 'Nghiên cứu kinh điển về tâm lý học hành vi', 260.000, 50, 230.000, 'BOOKS'),
                                                                                    ('Camera hành trình VietMap C62', 'Ghi hình Full HD, tích hợp GPS', 1590.000, 12, 1390.000, 'ELECTRONICS'),
                                                                                    ('Nồi cơm điện Toshiba 1.8L', 'Nấu cơm ngon, giữ ấm lâu', 990.000, 18, 890.000, 'HOME'),
                                                                                    ('Tai nghe Logitech G435', 'Tai nghe gaming không dây, siêu nhẹ', 1290.000, 22, 1190.000, 'ELECTRONICS'),
                                                                                    ('Sách Elon Musk - Tesla, SpaceX', 'Tiểu sử hấp dẫn về tỷ phú công nghệ', 190.000, 40, 160.000, 'BOOKS'),
                                                                                    ('Áo sơ mi nam Owen', 'Thiết kế trẻ trung, lịch sự', 499.000, 25, 420.000, 'FASHION'),
                                                                                    ('Apple Watch SE', 'Smartwatch cơ bản, theo dõi sức khỏe', 6390.000, 15, 5890.000, 'ELECTRONICS'),
                                                                                    ('Máy hút bụi cầm tay Xiaomi', 'Nhỏ gọn, dễ di chuyển, công suất lớn', 2290.000, 10, 1990.000, 'HOME'),
                                                                                    ('Balo laptop chống nước', 'Ngăn đựng riêng, đệm vai êm ái', 590.000, 30, 520.000, 'FASHION'),
                                                                                    ('Bút nhớ dòng Stabilo Boss', 'Màu sắc nổi bật, không lem mực', 28.000, 100, 25.000, 'STATIONERY'),
                                                                                    ('Sách Tôi thấy hoa vàng trên cỏ xanh', 'Tác phẩm nổi tiếng của Nguyễn Nhật Ánh', 98.000, 60, 85.000, 'BOOKS'),
                                                                                    ('Máy in Canon LBP 2900', 'Máy in laser A4 văn phòng, dễ sử dụng', 2990.000, 8, 2790.000, 'ELECTRONICS'),
                                                                                    ('Loa Bluetooth Xiaomi', 'Loa nhỏ gọn, âm thanh tốt', 690.000, 40, 620.000, 'ELECTRONICS'),
                                                                                    ('Giày lười nam Bitis', 'Chất liệu bền, dễ phối đồ', 420.000, 30, 380.000, 'FASHION'),
                                                                                    ('Máy xay sinh tố Philips', 'Xay nhuyễn mọi loại trái cây, rau củ', 990.000, 12, 890.000, 'HOME'),
                                                                                    ('Bút lông bảng Thiên Long', 'Mực đậm, viết êm, dễ xóa', 10.000, 150, 8.000, 'STATIONERY'),
                                                                                    ('Sách Cà phê cùng Tony', 'Tản văn truyền cảm hứng', 120.000, 70, 100.000, 'BOOKS'),
                                                                                    ('Áo hoodie nam form rộng', 'Phong cách streetwear, chất nỉ dày', 590.000, 22, 499.000, 'FASHION'),
                                                                                    ('Smart TV LG 43"', 'TV 4K UHD, hỗ trợ Netflix, Youtube', 6790.000, 9, 6290.000, 'ELECTRONICS'),
                                                                                    ('Nồi lẩu điện Sunhouse', 'Nấu nhanh, chống dính, dễ rửa', 590.000, 20, 520.000, 'HOME'),
                                                                                    ('Giày cao gót nữ Vascara', 'Thiết kế thanh lịch, cao 5cm', 990.000, 18, 890.000, 'FASHION'),
                                                                                    ('Sách Dế mèn phiêu lưu ký', 'Truyện thiếu nhi nổi tiếng của Tô Hoài', 75.000, 90, 60.000, 'BOOKS'),
                                                                                    ('Camera hành trình GoPro Hero 11', 'Quay video 5.3K, chống rung mạnh, chống nước', 11900.000, 14, 10500.000, 'ELECTRONICS'),
                                                                                    ('Loa Bluetooth Marshall Emberton II', 'Âm thanh sống động, thiết kế cổ điển, pin 30h', 4290.000, 25, 3900.000, 'ELECTRONICS');
